### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by inexistence** [iampomelo/mercury#1]
* Use `async/await` instance of using `Promise`. It's more simple.
* Transform `callback` into `Promise` or `async/await`.
* Use services but not database directly in controller. Let service operates database.Better for some reusing situation. *PS: More rigorous, services handle logic, Dao or Repository operates database.*
* You may thought it's not necessary for your little project, but if you use `mongoose`, table can be single model class, easiler to been defined and used. For example, table `user` can be `models/user.js` where defines its structs and exports User Instance.

**Comment by iampomelo** [comment]
You r right, the project has lots of shortcomings. I learn more this year and i can code better now.

**Comment by inexistence** [comment]
Nice, expecting ur cool project!
